version: "3"
services:
    vscode:
        container_name: vscode
        build:
            context: .
        volumes:
            - "./projects:/home/coder/project"
            - "~/.local/share/vscode:/home/coder/.local/share/code-server"
        ports:
            - "8080:8080"
        restart: always
        command: --no-auth --allow-http
