version: "3"
services:
    vscode:
        container_name: vscode
        build:
            context: .
        volumes:
            - "~/vscode-server/local:/home/coder/.local"
            - "~/vscode-server/projects:/home/coder/project"
            - "~/vscode-server/cache:/home/coder/.cache"
        ports:
            - "8443:8443"
        restart: always
        command: --no-auth
