version: "3"
services:
    vscode:
        container_name: vscode
        build:
            context: .
        volumes:
            - "./projects:/home/coder/project"
            - "~/.local/share/vscode:/home/coder/.local/share/code-server"
        ports:
            # With SSL
            - "443:8443"
            # With HTTP
            #- "80:8443"
        restart: always
        command: --no-auth # if using proxy add: --allow-http
