version: "3"
services:
    vscode:
        container_name: vscode
        build:
            context: .
        volumes:
            - "~/vscode-server/projects:/home/coder/project"
            - "~/vscode-server/.local:/home/coder/.local"
            - "~/vscode-server/.cache:/home/coder/.cache"
        ports:
            - "8080:8080"
        restart: always
        command: --auth none
